### ISSUE TITLE
bundle instances

### ISSUE THREAD

**Issue by t1** [t1/deployer#14]
Multiple instances of one bundle:

```
bundles:
  app:
    version: 1.0
    instances:
      app1:
        version: 1.1
      app2:
        version: 1.2
```
