### ISSUE TITLE
default root.bundle

### ISSUE THREAD

**Issue by t1** [t1/deployer#18]
```
bundles:
  ${regex(root-bundle-name or hostName(), bundle-to-host-name or «(.*?)\d*»)}:
    group-id: ${root-bundle-group or default.group-id or domainName()}
    version: ${version}
```
