### ISSUE TITLE
Variables dont work in log-handler properties

### ISSUE THREAD

**Issue by t1** [t1/deployer#69]
In this example, `$${xxx}` should become `${xxx}`, but `${name}` should be resolved. Both don't seem to work!

```yaml
log-handlers:
  FOO-JSON:
    type: custom
    module: xxx
    class: yyy
    properties:
      foo: $${xxx}/${name}
```
